import os
import sys
import time
import logging
import asyncio
from fastapi import FastAPI
from app.config import Settings
from app.services.inference import InferenceService
from app.routes import health, predict

# Setup standard logging format and root logger config
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)

logger = logging.getLogger("backend_api")

settings = Settings()

app = FastAPI(
    title="OrnithoAI - Bird Species Classifier Backend",
    description="A modular FastAPI backend serving a PyTorch-based bird classifier.",
    version="1.0.0"
)

# Attach routes
app.include_router(health.router)
app.include_router(predict.router)

@app.on_event("startup")
async def startup_event():
    model_path = settings.model_path
    classes_path = settings.classes_path
    
    logger.info(f"FastAPI Backend Startup: Checking for required model files at:")
    logger.info(f"  - Weights path: {model_path}")
    logger.info(f"  - Classes path: {classes_path}")

    # Set up wait parameters: 5-minute timeout (300 seconds)
    start_time = time.time()
    timeout = 300.0  # 5 minutes
    poll_interval = 5.0
    
    while not (os.path.exists(model_path) and os.path.exists(classes_path)):
        elapsed = time.time() - start_time
        if elapsed >= timeout:
            logger.critical(
                f"STARTUP TIMEOUT ERROR: Model files were not generated by the training module "
                f"within the 5-minute ({timeout}s) limit. Exiting FastAPI."
            )
            # Terminate application startup cleanly by exiting the process
            sys.exit(1)
            
        remaining = int(timeout - elapsed)
        logger.warning(
            f"Model files not found yet. The backend cannot serve predictions without them. "
            f"Waiting (polling again in {poll_interval}s... {remaining}s left until timeout)."
        )
        await asyncio.sleep(poll_interval)

    logger.info("Success! All required model files detected. Initializing Inference Service...")
    
    # Initialize the InferenceService and load the weights
    try:
        service = InferenceService(
            model_path=model_path,
            classes_path=classes_path,
            model_name=settings.MODEL_NAME
        )
        service.load_model()
        
        # Cache the service instance in application state
        app.state.inference_service = service
        logger.info("FastAPI initialization completed successfully.")
    except Exception as e:
        logger.critical(f"FATAL ERROR: Failed to load model weights or config: {str(e)}", exc_info=True)
        sys.exit(1)
